### ISSUE TITLE
safetensors dependency

### ISSUE THREAD

**Issue by oscarnevarezleal** [cloneofsimo/lora#87]
I believe #84 [introduced](https://github.com/cloneofsimo/lora/blob/66c18d31dbfcae07c785aa41770af69d54b5d29f/lora_diffusion/lora.py#L222) a _safetensors_ dependency but it's not specified in requirements.txt

**Comment by hafriedlander** [comment]
It's not supposed to be required, but it is currently because dreambooth calls save_safeloras indiscriminately. I'll add a PR soon.

My intent was that safetensors will be required to save safetensors, but not to load them (there's a pure python version), and that pytorch pickles would remain an option.

(I'd personally prefer if safetensors became the default, but that's up to @cloneofsimo and the community generally).

**Comment by hafriedlander** [comment]
https://github.com/cloneofsimo/lora/pull/101 should fix this

**Comment by hafriedlander** [comment]
This should be fixed now #101 is merged @oscarnevarezleal - feel free to reopen if something still breaks without safetensors installed.
